project:
  type: website
  output-dir: ../docs

website:
  title: "R. Mulhern"
  navbar:
    search: true
    
    tools: 
      - icon: github
        href: https://github.com/remulhern
      - icon: substack
        href: https://www.equalwaterlab.com/
      - text: "{{{< ai google-scholar >}}}"
        href: https://scholar.google.com/citations?user=h68E0NIAAAAJ&hl=en 
        
    left:
      - text: "Home"
        href: index.qmd
      - text: "ENVS 3030"
        href: 3030/syllabus.qmd
      - text: "ENVS 4800"
        href: 4800/syllabus.qmd
        
  sidebar:
    - title: "ENVS 3030"
      #style: "docked"
      search: true
      contents:
        - 3030/syllabus.qmd
        - 3030/schedule.qmd

    - title: "ENVS 4800"
      contents:
        - 4800/syllabus.qmd
        - 4800/schedule.qmd
        # navigation items
        
  page-footer: 
    left: "Copyright 2025, Riley Mulhern" 


format:
  html:
    #theme:
    #  - cosmo
    #  - brand
    css: styles.css
    toc: true

editor: visual

